services:

    app_test:
        build: 
            context: .
            dockerfile: ./docker/Dockerfile.tests
        depends_on:
            db_test:
                condition: service_healthy
        command: "python -m pytest -v /app"
    
    db_test: 
        container_name: postgres_test
        hostname: ${POSTGRES_HOST}
        image: postgres:latest
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        expose:
            - ${POSTGRES_PORT}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: on-failure
        volumes: []
        