services:

    app:
        build: 
            context: .
            dockerfile: ./docker/Dockerfile

        env_file:
            - .env
        depends_on:
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        ports:
            - ${APP_PORT}:${APP_CONTAINER_PORT}
    redis:
        image: redis:latest
        container_name: ${REDIS_HOST}
        hostname: ${REDIS_HOST}
        environment:
            - REDIS_PASSWORD=${REDIS_USER_PASSWORD}
            - REDIS_USER=${REDIS_USER}
            - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
        ports:
            - ${REDIS_PORT}:${REDIS_CONTAINER_PORT}
        deploy:
            resources:
                limits:
                   cpus: '0.50'
                   memory: 512M
                reservations:
                   cpus: '0.25'
                   memory: 256M
        command: >
            sh -c '
                mkdir -p /usr/local/etc/redis &&
                echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
                echo "requirepass $REDIS_USER_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
                echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
                echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
                echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
                echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
                redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
            '
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "$REDIS_USER_PASSWORD", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true
    postgres:
        container_name: ${POSTGRES_HOST}
        hostname: ${POSTGRES_HOST}
        image: postgres:latest
        restart: always
        env_file:
            - ".env"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
        
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: rabbitmq
        container_name: rabbitmq
        ports:
            - "${RABBITMQ_PORT}:${RABBITMQ_CONTAINER_PORT}"
            - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_CONTAINER_PORT}"
        env_file:
            - ".env"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    minio:
        image: minio/minio:latest
        container_name: minio
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - MINIO_DEFAULT_BUCKETS=buck1
        command: [ "server", "--console-address", ":9001", "/data" ]
        volumes:
            - minio_data:/data
        ports:
            - "${MINIO_S3_PORT}:${MINIO_S3_CONTAINER_PORT}"
            - "${MINIO_MANAGEMENT_PORT}:${MINIO_MANAGEMENT_CONTAINER_PORT}"
        env_file:
            - ".env"

    maildev:
      image: maildev/maildev
      environment:
        - TZ=Europe/Moscow
        - MAILDEV_WEB_PORT=${MAILDEV_WEB_CONTAINER_PORT}
        - MAILDEV_SMTP_PORT=${MAILDEV_SMTP_CONTAINER_PORT}
      ports:
        - "${MAILDEV_WEB_PORT}:${MAILDEV_WEB_CONTAINER_PORT}"
        - "${MAILDEV_SMTP_PORT}:${MAILDEV_SMTP_CONTAINER_PORT}"
      env_file:
            - ".env"
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
volumes:
    postgres_data:
    rabbitmq-data:
    minio_data: